# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
permalink: pretty
title: "World Biomimetic Challenges & Awards"
subtitle: "Biomimetics, a bioinspirer cosmovision"
tsgline: "An emerging social, cultural, economic and industrial reality"
email: info@biomimeticchallengesawards.com
date: "22 June"
location: Barcelona
description: > # this means to ignore newlines until "baseurl:"
  Next 22th June starts the first edition of World Biomimetics Challenges & Awards in collaboration with In(3D)dustry World Congress (Fira de Barcelona). The event is well underway for the coming World Biomimetic Experience Summit 2017 that will get to know a new social, economic and industrial reality by a bioinspirer Cosmo vision.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.biomimeticchallengesandawards.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
sass:
  style: compressed
twitter: WBChaA

twitter-sentence: "| Enjoy #WBChA, #Biomimetics via @WBChaA"

author:
  name: 'Ramon Gil'
  url: https://twitter.com/freecates
  email: rgil@oxygen.cat

gems:
  - jekyll-redirect-from

# Build settings
